Project MID/RMS/RMS/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMS.Repositories;
using RMS.Models.EF;
using RMS.Models.VM;

namespace RMS.Controllers
{
    [Authorize]
    public class ManagerController : Controller
    {
        // GET: Manager

        public ActionResult List()
        {
            var p = ManagersDetailRepo.GetAll();
            return View(p);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var p = ManagersDetailRepo.Get(Id);
            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(ManagersDetail pd)
        {
            ManagersDetailRepo.Edit(pd);
            return RedirectToAction("List");
        }
    }
}

Project MID/RMS/RMS/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RMS.Repositories;
using RMS.Models.EF;
using RMS.Models.VM;

namespace RMS.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            var p = ProductRepo.GetAll();
            return View(p);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product p)
        {
            var db = new RMSEntities();
            db.Products.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var p = ProductRepo.Get(Id);
            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(Product pd)
        {
            ProductRepo.Edit(pd);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var p = ProductRepo.Get(Id);
            return View(p);
        }

        [HttpPost]
        public ActionResult Delete(Product pd)
        {
            var db = new RMSEntities();
            var product = (from p in db.Products
                           where p.Id == pd.Id
                           select p).FirstOrDefault();
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Project MID/RMS/RMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Restaurant Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Product Index", "Index", "Product")</li>
                    <li>@Html.ActionLink("Delivery Index", "Index", "Deliveryman")</li>
                    <li>@Html.ActionLink("Manager Index", "List", "Manager")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="text-align:center;">&copy; @DateTime.Now.Year - Advanced .Net (B)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>